### ISSUE TITLE
Research and select fonts

### ISSUE THREAD

**Issue by dannyvsm** [Frictionless-Faction/FricFracChat#24] opened 2021-07-15 16:00 UTC
Choosing web-safe fonts that are accessible to various visual needs that can also suit our brand and compliments supporting font choices.

**Comment by RomanHyde** [comment] 2021-07-16 07:12
I've assigned this to in progress. Let me know how you get on with this so I can add it to the Figma plan.
Include fonts that you looked at (and liked) that you didn't end up choosing as well so we can share your thought process. Thanks.

**Comment by RomanHyde** [comment] 2021-07-16 11:27
I'm really enjoying your work so far and have added the suggested fonts to the figma UI design board.

**Comment by dannyvsm** [comment] 2021-07-19 09:35
I'm feeling very confident with the fonts chosen, if everyone is happy I'll close the issue and integrate them throughout the project

**Comment by RomanHyde** [comment] 2021-07-19 11:02
The issue is being closed as it has been complete. Thanks for picking the fonts, Danny.

**Closed as completed by RomanHyde** 2021-07-19 11:02 UTC
Labels: enhancement
